Generate 3d primitives using Buttons
UWRealityLab/xrcapstone22wi-team8 pull request #11
Opened 2022-01-29 07:35 UTC by KH-Kyle

TODO

2022-01-29 07:49 UTC, KH-Kyle commented
## TODO
- Refine the UI of Dashboard when merging with the brushes.
- Fix Dashboard relative to the camera.

These would be done with teammates before MVP

2022-01-29 08:10 UTC, ApolloZhu requested changes
The prefabs look exactly as named, and the dashboard looks like the included demo 👍 

**However**, you should update variable and function names to match the coding standards. Remember to double-check to make sure nothing is broken after renaming 😉

2022-01-29 08:10 UTC, ApolloZhu commented on Boardless/Assets/Scripts/ObjectGenerator.cs
> +    public void generate()
public members should capitalize first letter per coding convention: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#pascal-case

2022-01-29 08:10 UTC, ApolloZhu commented on Boardless/Assets/Scripts/ObjectGenerator.cs
> +    public void generate()
public members should capitalize the first letter per coding convention: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#pascal-case

2022-02-03 19:23 UTC, ApolloZhu approved these changes

2022-02-05 09:12 UTC, merged