Create week3.md
UWRealityLab/xrcapstone22wi-team8 pull request #30
Opened 2022-02-12 05:14 UTC by penpenLoveUwU

2022-02-12 05:18 UTC, ApolloZhu requested changes
1. There were 2 pull requests requiring review from week 3, see https://github.com/UWRealityLab/xrcapstone22wi-team8/issues/13
2. Let’s capitalize all list items (i.e. capitalize “b” in “brush” on line 20)
3. Course staff’s feedback for Week 4 snippet says that our summary is too vague, but I’m not sure how exactly we can be more detailed

2022-02-12 05:19 UTC, ApolloZhu commented on docs/content/en/snippets/week3.md
> +Next week, we'll refine our individual functions and pull everything together and hopefully and the "multiuser".
```suggestion
Next week, we'll refine our individual functions and pull everything together, and hopefully the "multiuser".
```

2022-02-12 05:20 UTC, penpenLoveUwU commented on docs/content/en/snippets/week3.md
> +Next week, we'll refine our individual functions and pull everything together and hopefully and the "multiuser".
I have fixed this and the "Brush". I think it is fine to have week3 like this because this is before week4.

2022-02-12 08:18 UTC, ApolloZhu commented on docs/content/en/snippets/week3.md
> +Next week, we'll refine our individual functions and pull everything together and hopefully and the "multiuser".
I see. Please add the two PRs for review by staff with one sentence description for each, then this should be good to go

2022-02-14 05:02 UTC, penpenLoveUwU reviewed
update again

2022-02-14 05:03 UTC, penpenLoveUwU reviewed
hi

2022-02-14 05:10 UTC, ApolloZhu approved these changes
Thanks for the updates

2022-02-14 05:11 UTC, merged